.github/workflows/build-and-test.yml

The v2 version uses node12 which is deprecated.

ci: Bump codecov/codecov-action to v3

---

.github/workflows/benchmark.yml
benchmark/disk.c
benchmark/disk_kaio.c
benchmark/disk_parse.c
benchmark/disk_parse.h

This allows running multiple scenarios with a single command invokation.

Add matrix support in the benchmark disk command

---

.github/workflows/benchmark.yml
Makefile.am
tools/benchmark/disk.c
tools/benchmark/disk_parse.c
tools/benchmark/fs.c
tools/benchmark/fs.h
tools/benchmark/main.c
tools/benchmark/report.c
tools/benchmark/report.h
tools/benchmark/submit.c
tools/benchmark/submit.h
tools/benchmark/submit_options.h
tools/benchmark/submit_parse.c
tools/benchmark/submit_parse.h

This adds a new `submit` command to `raft-benchmark`, for benchmarking sequential append operations of new entries to the log.

Add "submit" command to raft-benchmark

---

tools/benchmark/disk_uring.c

This links the write operation to the fsync operation, so that the latter won't be started until the former has completed.

[benchmark] disk: Ensure that fsync happens after write in io_uring

---

tools/benchmark/disk.c
tools/benchmark/disk_kaio.c
tools/benchmark/disk_kaio.h
tools/benchmark/disk_pwrite.c
tools/benchmark/disk_pwrite.h
tools/benchmark/disk_uring.c
tools/benchmark/disk_uring.h
tools/benchmark/report.c
tools/benchmark/report.h
tools/benchmark/submit.c
tools/benchmark/timer.c
tools/benchmark/timer.h

Use histograms instead of arrays of exact latency measurements. That allows to have benchmarks with a longer time span, without any significant loss in accuracy.

Use histograms for tracking latency in benchmarks

---

Makefile.am
tools/benchmark/disk.c
tools/benchmark/disk_parse.c
tools/benchmark/disk_parse.h
tools/benchmark/report.c
tools/benchmark/tracing.c
tools/benchmark/tracing.h

Add a new `--tracing` flag to support tracing kernel activity via debugfs.

benchmark: Use debugfs for tracing kernel activity

---

.github/workflows/benchmark.yml

Don't run benchmarks against btrfs/zfs and in buffered mode, since that's slowler.

[workflows] benchmark: Dial down testing matrix

---

tools/benchmark/disk.c
tools/benchmark/disk_options.c
tools/benchmark/disk_options.h
tools/benchmark/disk_parse.c

No need to use buffered I/O, since it's slower in theory and also in practice.

[benchmark] disk: Drop the --mode option, use only direct I/O

---

.github/workflows/benchmark.yml

Use the generic scripts from the `cowsql/cowsq-ci` branch instead of ad-hoc logic.

[workflows] benchmark: Use cowsql/cowsql-ci instead of ad-hoc logic

---

tools/benchmark/disk.c
tools/benchmark/disk_options.h
tools/benchmark/disk_parse.c
tools/benchmark/disk_parse.h
tools/benchmark/disk_uring.c
tools/benchmark/disk_uring.h
tools/benchmark/tracing.c
tools/benchmark/tracing.h

This is no longer needed, since the cowsql-ci machinery takes care of expanding matrixes of test combinations.
Also, enable kernel tracing only during actual writes, to avoid spurious event entries (e.g. io_uring setup).

[benchmark] disk: Drop command line options matrix

---

tools/benchmark/disk.c
tools/benchmark/fs.c
tools/benchmark/fs.h

Histogram resolution and buckets are now dynamically adjusted according to the underlying kernel storage driver (NVMe, nullb, etc), so timings can be a bit more accurate.

benchmark/disk: Adjust histogram buckets according to storage driver

---

tools/benchmark/disk.c
tools/benchmark/disk_uring.c
tools/benchmark/disk_uring.h
tools/benchmark/tracing.c
tools/benchmark/tracing.h

Instead of waiting for I/O completion using `io_uring_enter()` (which blocks and then resumes the thread), poll the completion queue directly. This results in slightly better performance.

benchmark/disk: Poll io_uring completion queue

---

src/replication.h
test/integration/test_snapshot.c

Add an explicit test for receiving AppendEntries requests while installing a
snapshot, making sure that those entries are properly ignored and their memory
released.

test_snapshot: Receive AppendEntries while installing a snapshot

---

src/log.h
src/replication.c

The true branch of the if statement being removed can't be taken, because of the reason explained in the comment.
This code was indeed untested.

replication: Replace if statement with assertion

---

tools/benchmark/disk.c
tools/benchmark/disk_uring.c
tools/benchmark/fs.c
tools/benchmark/fs.h

We were effectively already pre-writing the file, by probing the possible direct I/O buffer sizes, however we were doing that only up to 1M.
This change now explicitly pre-writes the entire file.

benchmark/disk: Pre-write the benchmark file to allocate extents

---

tools/benchmark/disk.c
tools/benchmark/disk_uring.c
tools/benchmark/fs.c
tools/benchmark/fs.h
tools/benchmark/profiler.c
tools/benchmark/profiler.h

Make the profiler smarter about the commands it processes, filtering out spurious commands that are actually triggered by the rest of the system, not by the benchmark.

benchmark/disk: Add more block/nvme command profiler checks

---

tools/benchmark/disk.c
tools/benchmark/disk_options.h
tools/benchmark/disk_parse.c
tools/benchmark/fs.c
tools/benchmark/profiler.c
tools/benchmark/profiler.h

There is a bit of overhead that comes from using perf_event_open() to measure the performance of the various kernel sub-systems.
This feature is now off by default, and must be enabled using the new --perf command line option.

benchmark/disk: Make kernel performance measuring optional

---

tools/benchmark/submit.c
tools/benchmark/submit_options.h
tools/benchmark/submit_parse.c

The command line flags now match the ones of "benchmark disk".

benchmark/submit: Adjust command line arguments

---

src/uv_append.c

We actually don't track that there are pending segment writer close operations, so this call to uvMaybeFireCloseCb() can't really unblock anything waiting on it.
On the contrary, if it fires after the close callback has actually been fired, it causes a double free:
==199067==ERROR: AddressSanitizer: attempting double-free on 0x602000000010 in thread T0:
#0 0x7fd5e44d7288 in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:52
#1 0x7fd5e4b5a259 in ioCloseCb src/raft.c:115
#2 0x7fd5e4b84861 in uvMaybeFireCloseCbReal src/uv.c:202
#3 0x7fd5e4afba70 in uv_run (/lib/x86_64-linux-gnu/libuv.so.1+0xfa70) (BuildId: 7f7f8c148150666c7b116bf98bf6e27f96c697a9)
#4 0x55b25438ebe5 in SubmitRun tools/benchmark/submit.c:314
#5 0x55b254388955 in main tools/benchmark/main.c:60
#6 …

uv/append: Don't call uvMaybeFireCloseCb in uvAliveSegmentWriterCloseCb

---

include/raft/uv.h
src/tracing.h
src/uv_append.c
src/uv_writer.c
src/uv_writer.h
test/integration/test_uv_truncate.c
test/integration/test_uv_truncate_snapshot.c
test/lib/tracer.c
test/lib/tracer.h
tools/benchmark/disk.c
tools/benchmark/disk_parse.c
tools/benchmark/fs.c
tools/benchmark/fs.h
tools/benchmark/report.c
tools/benchmark/report.h
tools/benchmark/submit.c

Add new tracing events to the libuv-based `raft_io` implementation to intercept the start and the end of disk writes, and use those events in the `raft-benchmark submit` command to report the latency of raw disk writes.

benchmark/submit: Report performance of disk writes

---

src/replication.c
test/integration/test_snapshot.c

It's okay to send an AppendEntries result to a leader that was not the same of the one that originally sent the snapshot, or that has bumped its term.
This makes the logic a bit simpler, since we don't need to track what the term was at the time the InstallSnapshot RPC was first received.
It also can speed up synchronization in case the new leader does not yet know the progress of the follower.

replication: Send AppendEntries result even if term changed

---

src/uv_encoding.c

The encoding of the AppendEntries and InstallSnapshot messages both contain a spurious unused word. This branch makes sure it gets zeroed, in case we want to re-purpose it later.

uv/encoding: Zero spurious word in AppendEntries and InstallSnapshot

---

src/replication.c
test/lib/fs.sh

Currently entries are applied synchronously by the FSM as soon as they get committed.
However, we want to also support disk-based FSMs that might need to apply entries asynchronously. Using commit_index instead of last_applied when taking snapshots means that the raft engine will be able to request a snapshot even if some entries are still being applied by the FSM. Consumer code will queue the snapshot request and process it when outstanding entries have been applied.

replication: For taking snapshots use commit_index, not last_applied

---

include/raft.h
src/client.c
src/convert.c
src/election.c
src/membership.c
src/progress.c
src/raft.c
src/recv.c
src/recv_append_entries.c
src/recv_install_snapshot.c
src/tick.c

Currently struct raft can get the current time by invoking the `time()` method of `struct raft_io`.
This field will be used to decouple `struct raft` from `struct raft_io`, so instead of asking `struct raft_io` what the current time is, `struct raft_io` or equivalent drivers will have the responsibility of telling struct raft what the current time is.

raft.h: Add raft->now field tracking what the current time is

---

src/uv_fs.c
src/uv_writer.c
test/lib/fs.sh

Use the per-request RWF_DSYNC flag (supported since Kernel 4.13), instead of opening the file with O_DSYNC.

uv/writer: Instead of opening files with O_DSYNC, use RWF_DSYNC

---

src/uv_fs.c
test/unit/test_uv_writer.c

Starting from kernel version 6.x, the xfs driver occasionally returns EAGAIN after the IOCB request has been submitted.

uv/fs: Handle xfs returning EAGAIN when probing for RWF_NOWAIT

---

Makefile.am
src/random.c
src/random.h
test/unit/test_random.c

This new builtin pseudo-random number generator will be used to eventually replace the `raft_io->random()` interface.

random: Add RandomRange() to generate a random number within a range

---

include/raft.h
src/election.c
src/fixture.c
src/raft.c

This plugs the internal PRNG into `struct raft`. For now the generator is seeded using `struct raft_io->random()`, but eventually it will be consumer's responsibility to initialize it.

raft: Plug pseudor-random number generator

---

include/raft.h
src/raft.c

The new `struct raft_task` structure and the associated `struct raft->tasks` queue will be used in the pull-based v1 API to inform consumers of what operations they need to carry.

raft.h: Add struct raft_task to track asynchronous tasks

---

include/raft.h
src/raft.c

The `raft_step()` function is going to be the core API of v1. It will won't call out to any external code (such as the `struct raft_io` interface), instead it will be a pure state-machine that consumer code can drive.

Add initial implementation of raft step()

---

Makefile.am
include/raft.h
src/client.c
src/election.c
src/legacy.c
src/legacy.h
src/recv.c
src/task.c
src/task.h
src/tick.c

The code has been updated to use the new `TaskPersistTermAndVote()` function, which creates a new `struct task_task`, instead of using the `raft_io` interface.

v1: Use TaskPersistTermAndVote instead of raft_io->set_term/set_vote

---

src/raft.c
src/recv.c
src/recv.h

The `LegacyForwardToRaftIo()` function will now forward to `raft_step()` all messages received by the `struct raft_io` interface.

recv: Update `recvCb` to use only `raft_step()` to process a message

---

include/raft.h
src/legacy.c
src/raft.c
src/recv_request_vote.c
src/task.c
src/task.h

Instead of using `raft_io->send()` to send RequestVote result messages, create a task of type `RAFT_SEND_MESSAGE`.

Use a task to send RequestVote result messages

---

src/election.c
src/membership.c
src/raft.c
src/recv_append_entries.c
src/recv_install_snapshot.c
src/replication.c
src/replication.h

Convert the code to use the `TaskSendMessage()` helper to queue a `RAFT_SEND_MESSAGE` task, instead of calling out to the legacy `raft_io->send()` interface.

v1: Use TaskSendMessage() to send messages

---

include/raft.h
src/legacy.c
src/progress.c
src/progress.h
src/raft.c
src/replication.c
src/replication.h
src/snapshot.c
src/task.c
src/task.h

The replication code has been updated to enqueue `RAFT_LOAD_SNAPSHOT` tasks instead of calling out to the legacy `raft_io->snapshot_get()` interface.

v1: Use TaskLoadSnapshot() instead of raft_io->snapshot_get()

---

include/raft.h
src/legacy.c
src/raft.c
src/replication.c
src/replication.h
src/task.c
src/task.h

When leader,  enqueue `RAFT_PERSIST_ENTRIES` tasks instead of calling out to the legacy raft_io->append_entries() interface.
A similar change for the follower state will be pushed in a follow-up PR.

v1: Use TaskPersistEntries() instead of raft_io->append_entries

---

src/fixture.c
src/legacy.c
src/replication.c
src/uv_truncate.c

Automatically use `raft_io->truncate()` when handling `RAFT_PERSIST_ENTRIES` tasks, so that call sites don't have to explicitly do that.
This is part of the contract of `RAFT_PERSIST_ENTRIES`, where all conflicting entries must be removed by the consumer code handling the task.

v1: Use raft_io->truncate() when handling RAFT_PERSIST_ENTRIES tasks

---

include/raft.h
src/legacy.c
src/raft.c
src/replication.c
src/replication.h
src/snapshot.c
src/start.c
src/task.c
src/task.h

Update the code to enqueue a `RAFT_PERSIST_SNAPSHOT` task instead of calling out the legacy `raft_io->snapshot_put()` interface.

v1: Use TaskPersistSnapshot() instead of raft_io->snapshot_put()

---

include/raft.h
src/legacy.c
src/raft.c
src/replication.c
src/replication.h
src/task.c
src/task.h

Enqueue tasks of type `RAFT_APPLY_COMMAND` instead of calling out the legacy `raft_fsm->apply()` interface.

v1: Use TaskApplyCommand() instead of raft_fsm->apply()

---

include/raft.h
src/legacy.c
src/raft.c
src/replication.c
src/replication.h
src/task.c
src/task.h

Enqueue a task of type `RAFT_TAKE_SNAPSHOT` in order to take a snapshot, instead of calling out to the legacy `raft_fsm->apply()` and `raft_io->snapshot_put()` interfaces.

v1: Use TaskTakeSnapshot() instead of raft_fsm->apply()

---

include/raft.h
src/legacy.c
src/replication.c
src/snapshot.c
src/start.c
src/task.c
src/task.h

Enqueue a `RAFT_SNAPSHOT_RESTORE` task instead of calling out to the legacy `raft_fsm->restore()` interface.

v1: Use TaskSnapshotRestore() instead of raft_fsm->restore()

---

include/raft.h
src/legacy.c

The disk-mode in dqlite depends on fsm->snapshot_async(), this commit re-adds it in a form that is sufficient to have dqlite tests pass.

raft.h: Re-add fsm->snapshot_async() method for backward compat

---

src/log.c
src/log.h
src/replication.c

Up to now there was no limit in the number of entries that a leader would send to a follower.
This introduces and hard-coded limit of 128, which at least prevents sending an unbounded number of entries.
Further refinements could make this limit configurable and/or also take into account the overall size of the entries being sent.

replication: Limit the number of entries included in AppendEntries

---

src/raft.c

Increase a bit timeouts in case we "detect" magic values used by the dqlite test suite, which are might lead to spurious failures on slow hardware.

timeout: Workaround time-dependent tests in dqlite

---

src/uv_ip.c
src/uv_tcp_connect.c

Tests where failing when running them on a system without a non-loopback network interface configured with IPv4.

Fix integration `raft_uv_transport` test failures

---

.github/workflows/downstream.yml

They were still referencing dqlite.

github: Point downstream workflow jobs to cowsql

---

include/raft.h
src/replication.c
src/task.c
src/task.h

Don't lag r->commit_index unnecessarily. It is now updated immediately in a single place, i.e. in replicationAppend(), which is called when receiving an AppendEntries message.
Before that change it was updated immediately only if the AppendEntries message was empty, while if the AppendEntries message was not empty, it would instead be updated asynchronously after the raft_io>append_entries() request completes and its callback is fired.

replication: Update r->commit index immediately

---

include/raft.h
src/legacy.c
src/raft.c
src/start.c

Improve the legacy compatibility code to properly handle `struct raft_restore_snapshot` tasks and execute them synchronously, as current client code expects, and then use `TaskRestoreSnasphot()` to restore snapshots at startup, instead of `struct raft_fsm->restore()`.

Use a task to restore snapshots at startup

---

configure.ac

Use a greater version than canonical/raft, making updates easier for distributions that have already packaged 0.18.0.

Release 0.18.1

---

src/legacy.c
src/raft.c
test/integration/test_init.c

In v1 there will be no need to pass raft_io and raft_fsm objects to raft_init(), this branch is a step in that direction.

Allow passing NULL io and fsm to raft_init()

---

include/raft.h
src/legacy.c
src/raft.c
src/replication.c
test/integration/test_snapshot.c

Instead of indirectly detect pending snapshot by looking at the `struct raft->snapshot.pending` and `struct raft->snapshot.put` fields, use explicit flags.
This is an incremental step towards having snapshots entirely driven by client code.

v1: Use flags to keep track of pending snapshots

---

include/raft.h
src/legacy.c
src/raft.c
src/replication.c
src/replication.h
src/restore.c
src/task.c
src/task.h

The `struct raft_restore_snapshot` and `struct raft_apply_command` tasks are now unnecessary, since that logic is going to be performed entirely by consumer code.

Drop unnecessary tasks

---

src/replication.c
test/integration/test_snapshot.c

Don't make followers wait for entries to be persisted on disk before advancing their commit index.

Apply committed entries eagerly on followers

---

src/replication.c
test/integration/test_snapshot.c

Revert the change in #95 that does not wait for entries to be persisted before advancing the commit index, since cowsql and raft_io are not yet prepared to handle the resulting edge cases.

replication: Revert eager commit index update

---

include/raft.h
src/convert.c
src/legacy.c
src/legacy.h
src/raft.c
src/restore.c

Instead of firing request callbacks synchronously when stepping down from leader, enqueue them in a new `legacy.requests` queue and fire them all after the running `raft_step()` call has returned.
This is a step towards decoupling `raft_step()` from `raft_fsm`/`raft_io` code.

v1: Fire request callbacks after raft step() when leadership is lost

---

include/raft.h
src/client.c
src/legacy.c
src/raft.c

The cowsql code needs to immediately detect when leadership lost after a `raft_step()` call, in order to close all client connections. So far, this has been done using a `uv_prepare` handle, but that is unreliable, since a lot of data might accumulate in the kernel TCP buffers when for example the process is paused (e.g. by the Jepsen nemesis), and the prepare handle does not have a chance to run.
This branch also fixes a few other bugs that were surfaced by Jepsen tests.

legacy: Add a `step_cb()` callback which filres after each `raft_step()` call

---

src/legacy.c

This is a corner case surfaced by jepsen tests. There should be a better solution, but this should fix the issue for now.

legacy: Don't take a snapshot if InstallSnapshot just failed

---

src/log.c
src/recv_append_entries.c
src/replication.c
test/unit/test_log.c

This fixes the following scenario, surfaced by Jepsen tests:
- a leader appends a new entry E to its log
- it also sends E to followers
- the disk write for E fails, while E is still being sent
- the leader steps down
- the ex-leader receives E from a follower, while it is still waiting for the original send operation of E to complete on all followers
In that case, E is still referenced by the local log when it gets received, which leads to an assertion failure.

log: Don't append duplicate entries that are still referenced

---

src/fixture.c
src/legacy.c
src/membership.c
src/membership.h
src/replication.c
src/tick.c
src/uv.c
src/uv.h
src/uv_truncate.c
test/integration/test_uv_recv.c
test/integration/test_uv_send.c

Move the code that triggers client callbacks out of `raft_step()` into the legacy compatibility layer. In v1, managing this kind of logic will be responsibility of user code.

v1: Trigger client callbacks after `raft_step()`

---

docs/_themes/material/layout.html

The 'style' keyword has been long deprecated and finally removed in Sphynx 7.0.0.
See https://github.com/sphinx-doc/sphinx/pull/11381.

docs: Use the 'styles' keyword instead of the deprecated 'style'

---

include/raft.h
src/client.c
src/client.h
src/convert.c
src/fixture.c
src/legacy.c
src/legacy.h
src/membership.c
src/progress.c
src/progress.h
src/raft.c
src/replication.c
src/replication.h
src/restore.c
src/tick.c
test/integration/test_snapshot.c

This moves the client requests queue and associated code from the core raft struct to the compatibility layer.

v1: Move pending client requests queue to the legacy compat code

---

test/lib/cluster.c
test/lib/cluster.h

Add initial test helpers for driving the v1 API. This is eventually going to replace the legacy `struct raft_fixture`.

v1: Initial test cluster helper

---

include/raft.h
src/election.c
src/election.h
src/log.c
src/log.h
src/raft.c
src/tracing.h
test/fuzzy/test_election.c
test/fuzzy/test_liveness.c
test/fuzzy/test_membership.c
test/fuzzy/test_replication.c
test/integration/test_apply.c
test/integration/test_assign.c
test/integration/test_barrier.c
test/integration/test_bootstrap.c
test/integration/test_election.c
test/integration/test_membership.c
test/integration/test_recover.c
test/integration/test_replication.c
test/integration/test_snapshot.c
test/integration/test_start.c
test/integration/test_tick.c
test/integration/test_transfer.c
test/lib/cluster.c
test/lib/cluster.h

This is a proof-of-concept test case that starts a single server with no persisted state.

test: Start a server with no on-disk state using the V1 API

---

include/raft.h
src/convert.c
src/election.c
src/raft.c
src/recv_append_entries.c
src/recv_install_snapshot.c
src/tick.c
test/integration/test_start.c
test/integration/test_tick.c
test/lib/cluster.c
test/lib/cluster.h

The new `test_cluster_step()` function is used to drive the cluster servers using the `raft_step()` API.

test: Add `test_cluster_step()` helper

---

src/client.c
src/election.c
src/progress.c
src/progress.h
src/raft.c
src/recv.c
src/recv_request_vote_result.c
src/replication.c
src/tick.c
test/integration/test_election.c
test/integration/test_start.c
test/integration/test_tick.c
test/lib/cluster.c
test/lib/cluster.h

Improve the v1-based test cluster machinery and convert a few existing tests to use that instead of the legacy `struct raft_fixture` from v0.

test: Convert some test cases to the v1 API

---

src/replication.c
test/integration/test_snapshot.c

Some call sites require to skip the progressShouldReplicate() check and force triggering replication immediately. For if probing a server fails because of missing entries, the leader should retry immediately without waiting for the heartbeat timeout to expire.

replication: Don't delay replication after a failed probe

---

src/client.c
src/client.h
src/convert.c
src/convert.h
src/election.c
src/election.h
src/log.c
src/log.h
src/membership.c
src/message.c
src/message.h
src/progress.h
src/recv.c
src/recv_append_entries.c
src/recv_append_entries_result.c
src/recv_install_snapshot.c
src/recv_request_vote.c
src/recv_request_vote_result.c
src/recv_timeout_now.c
src/replication.c
src/restore.c
src/tick.c
test/integration/test_election.c
test/integration/test_replication.c
test/integration/test_start.c
test/lib/cluster.c
test/lib/cluster.h

These tests now only use the v1 API and the associated test cluster machinery.

test: Convert replicaton tests to the v1 API

---

src/recv_request_vote_result.c
test/integration/test_election.c

When handling a RequestVote response, immediately check the term of the remote peer, before doing anything else.
This avoids checking if we are in candidate state twice, once at the beginning of the message handling and once after the term check, to handle the case where we step down.
Also, decide whether to perform an actual term bump or just a check based on the pre-vote flag of the RequestVote response being handled, and not based on whether we are in pre-vote phase or not. That's because we always want to bump our term if for any reason we discover an higher term (e.g. we receive a delayed non pre-vote response containing a newer term while in the meantime we have transitioned to pre-vote phase).

recv: Check remote term early on when handling RequestVote responses

---

configure.ac
src/byte.h
src/compress.c
src/configuration.c
src/uv_encoding.c
src/uv_fs.c
src/uv_metadata.c
src/uv_segment.c
src/uv_snapshot.c
src/uv_tcp_connect.c
src/uv_writer.c
test/integration/test_uv_init.c
test/integration/test_uv_set_term.c
test/integration/test_uv_tcp_listen.c
test/lib/fsm.c
test/unit/test_byte.c
test/unit/test_configuration.c

byte: Use `uint8_t*` instead of `void*` to meet aliasing rules

---

test/integration/test_uv_append.c

The code that finalizes the segment and renames it is run in the threadpool, and so could lag behind the main loop.
Fixes #120.

test: Fix flaky finalizeSegment assertion

---

configure.ac

Flags like -std and -pipe will be used unconditionally if available.

build: Separate regular and desired gcc options from hardening ones

---

include/raft.h
src/client.c
src/convert.c
src/election.c
src/election.h
src/legacy.c
src/legacy.h
src/membership.c
src/membership.h
src/progress.c
src/progress.h
src/raft.c
src/recv.c
src/replication.c
src/state.c
src/tick.c

A leadership transfer can now be carried on by firing a `RAFT_TRANSFER` event, without using `struct raft_transfer`, which is now kept only in the legacy backward compatibility layer.

v1: Add `raft_transferee()` API and associated internal logic changes

---

Makefile.am
include/raft.h.in
src/legacy.c
src/raft.c
src/recv.c
src/replication.c
src/replication.h
src/restore.c
src/snapshot.c
src/state.c
src/tick.c
test/integration/test_election.c
test/integration/test_membership.c
test/integration/test_replication.c
test/integration/test_snapshot.c
test/lib/cluster.c
test/lib/cluster.h

We are now using the `RAFT_SENT` event only to detect unreachable nodes, something that can be done by looking at the last contact time.

v1: Drop RAFT_SENT event

---

test/integration/test_catch_up.c
test/integration/test_election.c
test/integration/test_membership.c
test/integration/test_replication.c
test/integration/test_snapshot.c
test/integration/test_start.c
test/integration/test_tick.c
test/integration/test_transfer.c
test/lib/cluster.h
test/lib/macros.h

This is a convenience for saving some boilerplate in test code.

test: Add `CLUSTER_SUBMIT()` helper macro

---

src/replication.c

In order to decide whether a snapshot is needed, it is sufficient to check if the previous entry is present or not.

replication: Drop unnecessary check on `prev_index` being the last

---

src/progress.c
src/progress.h
src/replication.c
src/tick.c

Simplify call sites by moving some logic to `progress.c`.

progress: Add helpers for check online/recency status

---

src/progress.c
src/recv_append_entries.c
src/recv_append_entries_result.c
src/replication.c
src/tracing.c
test/integration/test_replication.c

There were a few cases were this value was set incorrectly. See individual commits for details.

replication: Fix the value of the last log index in AppendEntries results

---

include/raft.h.in
src/legacy.c
src/raft.c
src/replication.c
src/state.c
test/integration/test_replication.c

Limit the number of total entries that might be in-flight, i.e. that have been sent to a follower, but haven't yet been acknowledged.
Add `raft_set_max_inflight_entries()` to make that limit configurable.

replication: Limit maximum the number of total entries in-flight

---

include/raft.h.in
src/progress.c
src/progress.h
src/recv_append_entries.c
src/recv_install_snapshot.c
src/replication.c
src/replication.h
src/uv_encoding.c
test/integration/test_replication.c

If a follower is not persisting entries fast enough (e.g. because the disk is full), it will now stop accepting new entries, and will set a status flag for informing the leader of this.
In turn, the leader will stop sending new entries until the follower clears the flag.

replication: Set a saturated status flag when entries are lagging

---

include/raft.h.in
src/legacy.c
src/raft.c
src/replication.c
src/replication.h
test/integration/test_legacy.c
test/lib/cluster.c

v1: Drop status field from RAFT_PERSISTED_ENTRIES event

---

src/client.c
src/membership.c
src/membership.h
src/replication.c

We don't need to wait for entries to be persisted.

replication: Update commit index eagerly on followers

---

src/configuration.c
src/configuration.h
src/convert.c
src/uv_encoding.c
src/uv_tcp_connect.c

I identified three places where uninitialized memory was used for outgoing traffic using valgrind. This seemed to be caused by misc. struct members not being set explicitly although I have not investigated this in detail. I replaced some mallocs with callocs which seemed to solve the problem.

[atlesn] Fix misc. usage of uninitialized memory

---

src/recv_append_entries.c
src/recv_install_snapshot.c

In rejection pathways when receiving append entries or install snapshot frames, the `last_log_index` field of the internal representation of the append entries result frame was not set. This uninitialized value was then written to the encoding buffer for outgoing append entries result frame and sent out.

Use of uninitialized memory in outgoing append entries result frames

---

include/raft.h.in

when trying to include the raft.h with extern "C" it's not working because the do not allow sizeof checks with non-named structs. used for compatibility checks.

C++ compiler reject sizeof of anonymous structs

---

.github/workflows/downstream.yml
configure.ac
test/unit/test_uv_fs.c

The dqlite project no longer links to an external Raft library.

github: Don't run dqlite downstream tests
